import Foundation

struct DrugSeedData {
    static let psoriasisDrugs: [Drug] = [
        // TNF-alpha Inhibitors
        Drug(
            name: "Humira",
            genericName: nil,
            manufacturer: "AbbVie",
            drugClass: "TNF-alpha Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2008, 7, 25),
            administrationMethod: "Subcutaneous injection",
            dosing: "Initial: 80 mg, then 40 mg at week 1, then 40 mg every 2 weeks",
            sideEffects: ["Injection site reactions", "Upper respiratory infections", "Headache", "Hyperlipidemia"],
            approvedAgeGroups: ["Pediatric (≥15 kg)", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "TNF-alpha receptor antagonist",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Requires tuberculosis screening prior to initiation"
        ),
        
        Drug(
            name: "Etanercept",
            genericName: nil,
            manufacturer: "Amgen/Pfizer",
            drugClass: "TNF-alpha Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2004, 1, 30),
            administrationMethod: "Subcutaneous injection",
            dosing: "50 mg twice weekly for 12 weeks, then 50 mg once weekly",
            sideEffects: ["Injection site erythema", "Upper respiratory tract infections", "Headache"],
            approvedAgeGroups: ["Pediatric (≥2 years)", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "TNF-alpha receptor antagonist",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "First TNF inhibitor approved for psoriasis"
        ),
        
        Drug(
            name: "Enbrel",
            genericName: "Etanercept",
            manufacturer: "Amgen/Pfizer",
            drugClass: "TNF-alpha Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2004, 1, 30),
            administrationMethod: "Subcutaneous injection",
            dosing: "50 mg twice weekly for 12 weeks, then 50 mg once weekly",
            sideEffects: ["Injection site erythema", "Upper respiratory tract infections", "Headache"],
            approvedAgeGroups: ["Pediatric (≥2 years)", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "TNF-alpha receptor antagonist",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Marketed brand name for etanercept"
        ),
        
        Drug(
            name: "Infliximab",
            genericName: nil,
            manufacturer: "Janssen/Pfizer",
            drugClass: "TNF-alpha Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2006, 5, 19),
            administrationMethod: "Intravenous infusion",
            dosing: "5 mg/kg at weeks 0, 2, 6, then every 8 weeks",
            sideEffects: ["Infusion reactions", "Upper respiratory infections", "Headache", "Abdominal pain"],
            approvedAgeGroups: ["Pediatric (≥6 years)", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "TNF-alpha monoclonal antibody",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Requires in-office IV administration"
        ),
        
        Drug(
            name: "Remicade",
            genericName: "Infliximab",
            manufacturer: "Janssen",
            drugClass: "TNF-alpha Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2006, 5, 19),
            administrationMethod: "Intravenous infusion",
            dosing: "5 mg/kg at weeks 0, 2, 6, then every 8 weeks",
            sideEffects: ["Infusion reactions", "Upper respiratory infections", "Headache", "Abdominal pain"],
            approvedAgeGroups: ["Pediatric (≥6 years)", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "TNF-alpha monoclonal antibody",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Branded version of infliximab"
        ),
        
        Drug(
            name: "Infliximab-dyyb",
            genericName: nil,
            manufacturer: "Celltrion",
            drugClass: "TNF-alpha Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2016, 12, 22),
            administrationMethod: "Intravenous infusion",
            dosing: "5 mg/kg at weeks 0, 2, 6, then every 8 weeks",
            sideEffects: ["Infusion reactions", "Upper respiratory infections", "Headache"],
            approvedAgeGroups: ["Pediatric (≥6 years)", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "TNF-alpha monoclonal antibody",
            biosimilarOf: "Infliximab",
            isBiosimilar: true,
            notes: "First biosimilar approved for psoriasis in US"
        ),
        
        Drug(
            name: "Inflectra",
            genericName: "Infliximab-dyyb",
            manufacturer: "Celltrion",
            drugClass: "TNF-alpha Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2016, 12, 22),
            administrationMethod: "Intravenous infusion",
            dosing: "5 mg/kg at weeks 0, 2, 6, then every 8 weeks",
            sideEffects: ["Infusion reactions", "Upper respiratory infections"],
            approvedAgeGroups: ["Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "TNF-alpha monoclonal antibody",
            biosimilarOf: "Infliximab",
            isBiosimilar: true,
            notes: "Biosimilar to Remicade"
        ),
        
        // IL-17 Inhibitors
        Drug(
            name: "Secukinumab",
            genericName: nil,
            manufacturer: "Novartis",
            drugClass: "IL-17 Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2015, 1, 21),
            administrationMethod: "Subcutaneous injection",
            dosing: "300 mg at weeks 0, 1, 2, 3, 4, then monthly maintenance",
            sideEffects: ["Nasopharyngitis", "Diarrhea", "Upper respiratory tract infection"],
            approvedAgeGroups: ["Pediatric (≥2 years)", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "IL-17A inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "First IL-17 inhibitor for psoriasis"
        ),
        
        Drug(
            name: "Cosentyx",
            genericName: "Secukinumab",
            manufacturer: "Novartis",
            drugClass: "IL-17 Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2015, 1, 21),
            administrationMethod: "Subcutaneous injection",
            dosing: "300 mg at weeks 0, 1, 2, 3, 4, then monthly maintenance",
            sideEffects: ["Nasopharyngitis", "Upper respiratory tract infection"],
            approvedAgeGroups: ["Pediatric (≥2 years)", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "IL-17A inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Brand name for secukinumab"
        ),
        
        Drug(
            name: "Ixekizumab",
            genericName: nil,
            manufacturer: "Eli Lilly",
            drugClass: "IL-17 Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2016, 3, 22),
            administrationMethod: "Subcutaneous injection",
            dosing: "160 mg (two 80 mg injections) at week 0, then 80 mg at weeks 2, 4, 6, 8, 10, 12, then every 4 weeks",
            sideEffects: ["Upper respiratory tract infections", "Injection site reactions", "Oral candidiasis"],
            approvedAgeGroups: ["Pediatric (≥6 years)", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "IL-17A inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Rapidly effective with long-term improvements"
        ),
        
        Drug(
            name: "Taltz",
            genericName: "Ixekizumab",
            manufacturer: "Eli Lilly",
            drugClass: "IL-17 Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2016, 3, 22),
            administrationMethod: "Subcutaneous injection",
            dosing: "160 mg at week 0, then 80 mg at weeks 2, 4, 6, 8, 10, 12, then every 4 weeks",
            sideEffects: ["Upper respiratory tract infections", "Candida infections"],
            approvedAgeGroups: ["Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "IL-17A inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Brand name for ixekizumab"
        ),
        
        // IL-23 Inhibitors
        Drug(
            name: "Risankizumab",
            genericName: nil,
            manufacturer: "AbbVie",
            drugClass: "IL-23 Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2019, 4, 30),
            administrationMethod: "Subcutaneous injection",
            dosing: "150 mg at weeks 0, 4, then every 12 weeks",
            sideEffects: ["Upper respiratory tract infections", "Arthralgia", "Creatine phosphokinase elevation"],
            approvedAgeGroups: ["Pediatric (≥4.5 kg)", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "IL-23p19 inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Best-in-class efficacy with longest dosing interval"
        ),
        
        Drug(
            name: "Skyrizi",
            genericName: "Risankizumab",
            manufacturer: "AbbVie",
            drugClass: "IL-23 Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2019, 4, 30),
            administrationMethod: "Subcutaneous injection",
            dosing: "150 mg at weeks 0, 4, then every 12 weeks",
            sideEffects: ["Upper respiratory tract infections"],
            approvedAgeGroups: ["Pediatric", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "IL-23p19 inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Brand name for risankizumab"
        ),

        Drug(
            name: "Ustekinumab",
            genericName: nil,
            manufacturer: "Janssen",
            drugClass: "IL-12/23 Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2009, 9, 25),
            administrationMethod: "Subcutaneous injection",
            dosing: "45 mg or 90 mg at weeks 0 and 4, then every 12 weeks",
            sideEffects: ["Upper respiratory infections", "Headache", "Injection site reactions"],
            approvedAgeGroups: ["Pediatric (≥6 years)", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "IL-12/IL-23 inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Targets both IL-12 and IL-23 pathways"
        ),

        Drug(
            name: "Stelara",
            genericName: "Ustekinumab",
            manufacturer: "Janssen",
            drugClass: "IL-12/23 Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2009, 9, 25),
            administrationMethod: "Subcutaneous injection",
            dosing: "45 mg or 90 mg at weeks 0 and 4, then every 12 weeks",
            sideEffects: ["Upper respiratory infections", "Headache", "Injection site reactions"],
            approvedAgeGroups: ["Pediatric (≥6 years)", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "IL-12/IL-23 inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Brand name for ustekinumab"
        ),
        
        Drug(
            name: "Guselkumab",
            genericName: nil,
            manufacturer: "Janssen",
            drugClass: "IL-23 Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2017, 7, 21),
            administrationMethod: "Subcutaneous injection",
            dosing: "100 mg at weeks 0, 4, then every 8 weeks",
            sideEffects: ["Upper respiratory tract infections", "Pharyngitis", "Gastroenteritis"],
            approvedAgeGroups: ["Pediatric (≥15 kg)", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "IL-23 subunit p19 inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Well-tolerated with minimal infections compared to TNF inhibitors"
        ),
        
        Drug(
            name: "Tremfya",
            genericName: "Guselkumab",
            manufacturer: "Janssen",
            drugClass: "IL-23 Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2017, 7, 21),
            administrationMethod: "Subcutaneous injection",
            dosing: "100 mg at weeks 0, 4, then every 8 weeks",
            sideEffects: ["Upper respiratory infections", "Gastroenteritis"],
            approvedAgeGroups: ["Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "IL-23 p19 inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Brand name for guselkumab"
        ),
        
        Drug(
            name: "Tildrakizumab",
            genericName: nil,
            manufacturer: "Sun Dermatology/Almirall",
            drugClass: "IL-23 Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2018, 10, 17),
            administrationMethod: "Subcutaneous injection",
            dosing: "100 mg at weeks 0, 4, then every 12 weeks",
            sideEffects: ["Upper respiratory tract infections", "Headache"],
            approvedAgeGroups: ["Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "IL-23p19 inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Selective IL-23 antagonist"
        ),
        
        Drug(
            name: "Ilumya",
            genericName: "Tildrakizumab",
            manufacturer: "Sun Dermatology",
            drugClass: "IL-23 Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2018, 10, 17),
            administrationMethod: "Subcutaneous injection",
            dosing: "100 mg at weeks 0, 4, then every 12 weeks",
            sideEffects: ["Upper respiratory infections", "Headache"],
            approvedAgeGroups: ["Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "IL-23p19 inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Brand name for tildrakizumab"
        ),
        
        // Phosphodiesterase-4 Inhibitors
        Drug(
            name: "Apremilast",
            genericName: nil,
            manufacturer: "Celgene/Bristol Myers Squibb",
            drugClass: "Phosphodiesterase-4 Inhibitor",
            type: .small_molecule,
            fdaApprovalDate: dateFromComponents(2014, 9, 24),
            administrationMethod: "Oral tablet",
            dosing: "30 mg twice daily (after 5-day titration)",
            sideEffects: ["Diarrhea", "Nausea", "Headache", "Upper respiratory tract infection"],
            approvedAgeGroups: ["Pediatric (≥6 years)", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "Phosphodiesterase-4 inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Oral medication with good tolerability profile"
        ),
        
        Drug(
            name: "Otezla",
            genericName: "Apremilast",
            manufacturer: "Celgene",
            drugClass: "Phosphodiesterase-4 Inhibitor",
            type: .small_molecule,
            fdaApprovalDate: dateFromComponents(2014, 9, 24),
            administrationMethod: "Oral tablet",
            dosing: "30 mg twice daily",
            sideEffects: ["Diarrhea", "Nausea", "Headache"],
            approvedAgeGroups: ["Pediatric (≥6 years)", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "Phosphodiesterase-4 inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Brand name for apremilast"
        ),
        
        // JAK Inhibitors
        Drug(
            name: "Tofacitinib",
            genericName: nil,
            manufacturer: "Pfizer",
            drugClass: "JAK Inhibitor",
            type: .small_molecule,
            fdaApprovalDate: dateFromComponents(2018, 9, 10),
            administrationMethod: "Oral tablet",
            dosing: "5 mg twice daily",
            sideEffects: ["Upper respiratory tract infections", "Headache", "Diarrhea", "Lipid elevation"],
            approvedAgeGroups: ["Ages 12 and older", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "JAK1/JAK3 inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "First systemic JAK inhibitor for psoriasis"
        ),
        
        Drug(
            name: "Xeljanz",
            genericName: "Tofacitinib",
            manufacturer: "Pfizer",
            drugClass: "JAK Inhibitor",
            type: .small_molecule,
            fdaApprovalDate: dateFromComponents(2018, 9, 10),
            administrationMethod: "Oral tablet",
            dosing: "5 mg twice daily",
            sideEffects: ["Upper respiratory tract infections", "Headache"],
            approvedAgeGroups: ["Ages 12+", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "JAK1/JAK3 inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Brand name for tofacitinib"
        ),
        
        Drug(
            name: "Baricitinib",
            genericName: nil,
            manufacturer: "Eli Lilly",
            drugClass: "JAK Inhibitor",
            type: .small_molecule,
            fdaApprovalDate: dateFromComponents(2022, 6, 14),
            administrationMethod: "Oral tablet",
            dosing: "2 mg once daily or 4 mg once daily",
            sideEffects: ["Upper respiratory infections", "Headache", "Nausea"],
            approvedAgeGroups: ["Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "JAK1/JAK2 inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "JAK1/JAK2 preferential inhibitor"
        ),
        
        Drug(
            name: "Olumiant",
            genericName: "Baricitinib",
            manufacturer: "Eli Lilly",
            drugClass: "JAK Inhibitor",
            type: .small_molecule,
            fdaApprovalDate: dateFromComponents(2022, 6, 14),
            administrationMethod: "Oral tablet",
            dosing: "2 mg or 4 mg once daily",
            sideEffects: ["Upper respiratory infections", "Headache"],
            approvedAgeGroups: ["Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "JAK1/JAK2 inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Brand name for baricitinib"
        ),
        
        Drug(
            name: "Ruxolitinib",
            genericName: nil,
            manufacturer: "Incyte/Pfizer",
            drugClass: "JAK Inhibitor",
            type: .topical,
            fdaApprovalDate: dateFromComponents(2022, 8, 9),
            administrationMethod: "Topical cream",
            dosing: "Apply to affected areas twice daily",
            sideEffects: ["Application site irritation", "Contact dermatitis"],
            approvedAgeGroups: ["Adults"],
            indications: "Mild to moderate plaque psoriasis",
            biologicalTarget: "JAK1/JAK2 inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "First topical JAK inhibitor for psoriasis"
        ),
        
        Drug(
            name: "Opzelura",
            genericName: "Ruxolitinib cream",
            manufacturer: "Incyte/Pfizer",
            drugClass: "JAK Inhibitor",
            type: .topical,
            fdaApprovalDate: dateFromComponents(2022, 8, 9),
            administrationMethod: "Topical cream",
            dosing: "Apply to affected areas twice daily",
            sideEffects: ["Application site irritation"],
            approvedAgeGroups: ["Adults"],
            indications: "Mild to moderate plaque psoriasis",
            biologicalTarget: "JAK1/JAK2 inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Brand name for ruxolitinib cream"
        ),
        
        // Corticosteroids (Topical)
        Drug(
            name: "Clobetasol propionate",
            genericName: nil,
            manufacturer: "Multiple generic manufacturers",
            drugClass: "Topical Corticosteroid",
            type: .topical,
            fdaApprovalDate: dateFromComponents(1989, 1, 1),
            administrationMethod: "Topical application (cream, ointment, foam, shampoo)",
            dosing: "Apply thin layer to affected skin twice daily for up to 2 weeks",
            sideEffects: ["Skin atrophy", "Striae", "Telangiectasia", "Secondary infections"],
            approvedAgeGroups: ["Pediatric (≥1 year)", "Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "Glucocorticoid receptor agonist",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Highest potency topical steroid; not for prolonged use"
        ),
        
        Drug(
            name: "Triamcinolone acetonide",
            genericName: nil,
            manufacturer: "Multiple manufacturers",
            drugClass: "Topical Corticosteroid",
            type: .topical,
            fdaApprovalDate: dateFromComponents(1976, 1, 1),
            administrationMethod: "Topical application (cream, ointment, lotion)",
            dosing: "Apply thin layer to affected areas three times daily",
            sideEffects: ["Skin irritation", "Folliculitis", "Allergic contact dermatitis"],
            approvedAgeGroups: ["Pediatric", "Adults"],
            indications: "Mild to moderate plaque psoriasis",
            biologicalTarget: "Glucocorticoid receptor agonist",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Mid-potency steroid suitable for intertriginous areas"
        ),
        
        // Vitamin D Analogues
        Drug(
            name: "Calcipotriene",
            genericName: nil,
            manufacturer: "Multiple manufacturers",
            drugClass: "Vitamin D Analogue",
            type: .topical,
            fdaApprovalDate: dateFromComponents(1993, 1, 1),
            administrationMethod: "Topical ointment or cream",
            dosing: "Apply thin layer to affected areas once or twice daily",
            sideEffects: ["Transient irritation", "Facial dermatitis", "Hypercalcemia (rare)"],
            approvedAgeGroups: ["Adults"],
            indications: "Mild to moderate plaque psoriasis",
            biologicalTarget: "Vitamin D3 receptor agonist",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Can be used as monotherapy or with topical corticosteroids"
        ),
        
        Drug(
            name: "Dovonex",
            genericName: "Calcipotriene",
            manufacturer: "LEO Pharma",
            drugClass: "Vitamin D Analogue",
            type: .topical,
            fdaApprovalDate: dateFromComponents(1993, 1, 1),
            administrationMethod: "Topical ointment or cream",
            dosing: "Apply once or twice daily to affected areas",
            sideEffects: ["Transient irritation", "Hypercalcemia"],
            approvedAgeGroups: ["Adults"],
            indications: "Mild to moderate plaque psoriasis",
            biologicalTarget: "Vitamin D3 receptor agonist",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Brand name for calcipotriene"
        ),
        
        // Retinoids
        Drug(
            name: "Acitretin",
            genericName: nil,
            manufacturer: "Stiefel Labs/GSK",
            drugClass: "Oral Retinoid",
            type: .small_molecule,
            fdaApprovalDate: dateFromComponents(1997, 9, 25),
            administrationMethod: "Oral capsule",
            dosing: "25-50 mg daily with food",
            sideEffects: ["Xerosis", "Cheilitis", "Hepatotoxicity", "Hypertriglyceridemia", "Teratogenic"],
            approvedAgeGroups: ["Adults"],
            indications: "Severe psoriasis",
            biologicalTarget: "Retinoic acid receptor (RAR) agonist",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Highly teratogenic; requires strict contraception in women of childbearing age"
        ),
        
        Drug(
            name: "Soriatane",
            genericName: "Acitretin",
            manufacturer: "Stiefel Labs",
            drugClass: "Oral Retinoid",
            type: .small_molecule,
            fdaApprovalDate: dateFromComponents(1997, 9, 25),
            administrationMethod: "Oral capsule",
            dosing: "25-50 mg daily with food",
            sideEffects: ["Dry skin", "Lip inflammation", "Liver toxicity", "Teratogenic"],
            approvedAgeGroups: ["Adults (18+)"],
            indications: "Severe psoriasis",
            biologicalTarget: "RAR agonist",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Brand name for acitretin"
        ),
        
        // Methotrexate
        Drug(
            name: "Methotrexate",
            genericName: nil,
            manufacturer: "Multiple manufacturers",
            drugClass: "Immunosuppressant",
            type: .small_molecule,
            fdaApprovalDate: dateFromComponents(1982, 1, 1),
            administrationMethod: "Oral or subcutaneous injection",
            dosing: "7.5-25 mg once weekly",
            sideEffects: ["Bone marrow suppression", "Hepatotoxicity", "Nausea", "Oral ulcers"],
            approvedAgeGroups: ["Pediatric (≥3 years)", "Adults"],
            indications: "Moderate to severe psoriasis",
            biologicalTarget: "Dihydrofolate reductase inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Requires regular monitoring of blood counts and liver function"
        ),
        
        // Cyclosporine
        Drug(
            name: "Cyclosporine",
            genericName: nil,
            manufacturer: "Novartis/Multiple",
            drugClass: "Immunosuppressant",
            type: .small_molecule,
            fdaApprovalDate: dateFromComponents(1990, 12, 21),
            administrationMethod: "Oral microemulsion or IV infusion",
            dosing: "1.25-5 mg/kg/day in two divided doses",
            sideEffects: ["Hypertension", "Renal dysfunction", "Gingival hyperplasia", "Hypertrichosis"],
            approvedAgeGroups: ["Pediatric (≥18 months)", "Adults"],
            indications: "Severe psoriasis",
            biologicalTarget: "Calcineurin inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Effective but requires monitoring for nephrotoxicity"
        ),
        
        // PDE-4 Inhibitor
        Drug(
            name: "Roflumilast",
            genericName: nil,
            manufacturer: "Arcus Biosciences",
            drugClass: "Phosphodiesterase-4 Inhibitor",
            type: .topical,
            fdaApprovalDate: dateFromComponents(2022, 10, 12),
            administrationMethod: "Topical foam",
            dosing: "Apply to affected areas once daily",
            sideEffects: ["Application site reactions", "Headache", "Diarrhea"],
            approvedAgeGroups: ["Adults (≥18 years)"],
            indications: "Mild to moderate plaque psoriasis",
            biologicalTarget: "Phosphodiesterase-4 inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "First topical PDE-4 inhibitor for psoriasis"
        ),
        
        Drug(
            name: "Rayos",
            genericName: "Prednisone",
            manufacturer: "Ribapharm/Shire",
            drugClass: "Oral Corticosteroid",
            type: .small_molecule,
            fdaApprovalDate: dateFromComponents(2012, 7, 13),
            administrationMethod: "Oral tablet (delayed-release)",
            dosing: "Variable dosing based on severity",
            sideEffects: ["Immunosuppression", "Hyperglycemia", "Osteoporosis", "Mood changes"],
            approvedAgeGroups: ["Children", "Adults"],
            indications: "Severe psoriasis (short-term use)",
            biologicalTarget: "Glucocorticoid receptor agonist",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Used for acute flares; not for long-term management"
        ),
        
        Drug(
            name: "Brodalumab",
            genericName: nil,
            manufacturer: "Valeant/Bausch Health",
            drugClass: "IL-17 Receptor Antagonist (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2015, 2, 13),
            administrationMethod: "Subcutaneous injection",
            dosing: "210 mg at weeks 0, 1, 2, then every 2 weeks",
            sideEffects: ["Nasopharyngitis", "Upper respiratory infections", "Neutropenia"],
            approvedAgeGroups: ["Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "IL-17 receptor A antagonist",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Requires Risk Evaluation and Mitigation Strategy (REMS) due to suicidality concerns"
        ),
        
        Drug(
            name: "Bimzelx",
            genericName: nil,
            manufacturer: "UCB",
            drugClass: "IL-17A/IL-17F Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2023, 10, 17),
            administrationMethod: "Subcutaneous injection",
            dosing: "320 mg at weeks 0, 4, then every 8 weeks",
            sideEffects: ["Upper respiratory tract infections", "Oral candidiasis", "Diarrhea"],
            approvedAgeGroups: ["Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "IL-17A and IL-17F inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Approved for adults with moderate to severe plaque psoriasis"
        ),
        
        Drug(
            name: "Cimzia",
            genericName: nil,
            manufacturer: "UCB",
            drugClass: "TNF-alpha Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2008, 5, 27),
            administrationMethod: "Subcutaneous injection",
            dosing: "200 mg every other week",
            sideEffects: ["Injection site reactions", "Upper respiratory infections", "Rash"],
            approvedAgeGroups: ["Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "TNF-alpha inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Approved for adults with plaque psoriasis"
        ),
        
        Drug(
            name: "Orencia",
            genericName: nil,
            manufacturer: "Bristol Myers Squibb",
            drugClass: "T-cell Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2005, 12, 23),
            administrationMethod: "Intravenous infusion or subcutaneous injection",
            dosing: "Varies by indication and weight",
            sideEffects: ["Headache", "Upper respiratory infections", "Nausea"],
            approvedAgeGroups: ["Adults"],
            indications: "Psoriatic arthritis; also used in other autoimmune disease settings",
            biologicalTarget: "T-cell co-stimulation inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Listed in the PDF as a T-cell inhibitor for psoriatic disease"
        ),
        
        Drug(
            name: "Spesolimab",
            genericName: nil,
            manufacturer: "Boehringer Ingelheim",
            drugClass: "IL-36 Receptor Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2022, 9, 1),
            administrationMethod: "Intravenous infusion",
            dosing: "Single dose based on weight",
            sideEffects: ["Infection", "Headache", "Nausea"],
            approvedAgeGroups: ["Adults"],
            indications: "Generalized pustular psoriasis flares",
            biologicalTarget: "IL-36 receptor inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Included in the PDF as an IL-36R inhibitor"
        ),

        Drug(
            name: "SPEVIGO",
            genericName: "Spesolimab",
            manufacturer: "Boehringer Ingelheim",
            drugClass: "IL-36 Receptor Inhibitor (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2022, 9, 1),
            administrationMethod: "Intravenous infusion",
            dosing: "Single dose based on weight",
            sideEffects: ["Infection", "Headache", "Nausea"],
            approvedAgeGroups: ["Adults"],
            indications: "Generalized pustular psoriasis flares",
            biologicalTarget: "IL-36 receptor inhibitor",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Brand name for spesolimab"
        ),
        
        Drug(
            name: "Siliq",
            genericName: "Brodalumab",
            manufacturer: "Valeant",
            drugClass: "IL-17 Receptor Antagonist (Biologic)",
            type: .biologic,
            fdaApprovalDate: dateFromComponents(2015, 2, 13),
            administrationMethod: "Subcutaneous injection",
            dosing: "210 mg at weeks 0, 1, 2, then every 2 weeks",
            sideEffects: ["Nasopharyngitis", "Upper respiratory infections"],
            approvedAgeGroups: ["Adults"],
            indications: "Moderate to severe plaque psoriasis",
            biologicalTarget: "IL-17RA antagonist",
            biosimilarOf: nil,
            isBiosimilar: false,
            notes: "Brand name for brodalumab"
        )
    ]
    
    private static func dateFromComponents(_ year: Int, _ month: Int, _ day: Int) -> Date {
        var components = DateComponents()
        components.year = year
        components.month = month
        components.day = day
        return Calendar.current.date(from: components) ?? Date()
    }
}
